<?php

namespace Database\Seeders;

use App\Models\Hadith;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HadithSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $hadiths = [
            // ================= PRAYER HADITHS (1-10) =================
            [
                'id' => 1,
                'prayer_id' => 1, // Fajr
                'module' => 'prayer',
                'arabic_text' => 'مَنْ صَلَّى الْبَرْدَيْنِ دَخَلَ الْجَنَّةَ',
                'transliteration' => 'Man sallal-bardayni dakhalal-jannah.',
                'translation' => 'He who prays the two cool prayers (i.e., Fajr and Asr) will enter Paradise.',
                'source' => 'Sahih Bukhari 574, Sahih Muslim 635',
                'narrator' => 'Abu Musa Al-Ash\'ari',
                'topic' => 'Virtue of Fajr and Asr',
                'verified' => true,
            ],
            [
                'id' => 2,
                'prayer_id' => 1, // Fajr
                'module' => 'prayer',
                'arabic_text' => 'رَكْعَتَا الْفَجْرِ خَيْرٌ مِنَ الدُّنْيَا وَمَا فِيهَا',
                'transliteration' => 'Rak\'atal-fajri khayrun minad-dunya wa ma fiha.',
                'translation' => 'The two rakat (sunnah before) Fajr are better than this world and all that it contains.',
                'source' => 'Sahih Muslim 725',
                'narrator' => 'Aisha (ra)',
                'topic' => 'Virtue of Fajr Sunnah',
                'verified' => true,
            ],
            [
                'id' => 3,
                'prayer_id' => 2, // Dhuhr
                'module' => 'prayer',
                'arabic_text' => 'مَنْ حَافَظَ عَلَى أَرْبَعِ رَكَعَاتٍ قَبْلَ الظُّهْرِ وَأَرْبَعٍ بَعْدَهَا حَرَّمَهُ اللَّهُ عَلَى النَّارِ',
                'transliteration' => 'Man hafadha ala arba\'i raka\'atin qabladh-dhuhri wa arba\'in ba\'daha harramahullahu \'alan-nar.',
                'translation' => 'Whoever consistently observes four rakat before Dhuhr and four rakat after it, Allah will forbid him from the Fire.',
                'source' => 'Jami at-Tirmidhi 427, Sunan Abu Dawud 1269',
                'narrator' => 'Umm Habibah',
                'topic' => 'Virtue of Dhuhr prayers',
                'verified' => true,
            ],
            [
                'id' => 4,
                'prayer_id' => 3, // Asr
                'module' => 'prayer',
                'arabic_text' => 'رَحِمَ اللَّهُ امْرَأً صَلَّى قَبْلَ الْعَصْرِ أَرْبَعًا',
                'transliteration' => 'Rahimallahumra\'an salla qablal-\'asri arba\'a.',
                'translation' => 'May Allah have mercy on a person who prays four rakat before the Asr prayer.',
                'source' => 'Jami at-Tirmidhi 430',
                'narrator' => 'Abdullah ibn Umar',
                'topic' => 'Virtue of four rakat before Asr',
                'verified' => true,
            ],
            [
                'id' => 5,
                'prayer_id' => 4, // Maghrib
                'module' => 'prayer',
                'arabic_text' => 'صَلُّوا قَبْلَ صَلَاةِ الْمَغْرِبِ قَالَ فِي الثَّالِثَةِ لِمَنْ شَاءَ',
                'transliteration' => 'Sallu qabla salatil-maghrib, qala fit-thalithati liman sha\'a.',
                'translation' => 'Pray before the Maghrib prayer. He said it the third time: For whoever wills (to show it is voluntary).',
                'source' => 'Sahih Bukhari 1183',
                'narrator' => 'Abdullah Al-Muzani',
                'topic' => 'Voluntary prayer before Maghrib',
                'verified' => true,
            ],
            [
                'id' => 6,
                'prayer_id' => 5, // Isha
                'module' => 'prayer',
                'arabic_text' => 'مَنْ صَلَّى الْعِشَاءَ فِي جَمَاعَةٍ فَكَأَنَّمَا قَامَ نِصْفَ اللَّيْلِ',
                'transliteration' => 'Man sallal-\'isha\'a fi jama\'atin faka\'annama qama nisfal-layl.',
                'translation' => 'He who prays Isha in congregation is as if he has prayed half the night.',
                'source' => 'Sahih Muslim 656',
                'narrator' => 'Uthman ibn Affan',
                'topic' => 'Virtue of Isha in congregation',
                'verified' => true,
            ],
            [
                'id' => 7,
                'prayer_id' => 5, // Isha/Night
                'module' => 'prayer',
                'arabic_text' => 'مَنْ صَلَّى الْعِشَاءَ فِي جَمَاعَةٍ وَالْفَجْرَ فِي جَمَاعَةٍ كَانَ كَقِيَامِ لَيْلَةٍ',
                'transliteration' => 'Man sallal-\'isha\'a fi jama\'ah wal-fajra fi jama\'ah kana kaqiyami laylah.',
                'translation' => 'Whoever prays Isha in congregation and Fajr in congregation, it is as if he spent the entire night in prayer.',
                'source' => 'Jami at-Tirmidhi 221',
                'narrator' => 'Uthman ibn Affan',
                'topic' => 'Isha and Fajr Congregation',
                'verified' => true,
            ],
            [
                'id' => 8,
                'prayer_id' => null, // Special/Witr
                'module' => 'prayer',
                'arabic_text' => 'إِنَّ اللَّهَ وِتْرٌ يُحِبُّ الْوِتْرَ فَأَوْتِرُوا يَا أَهْلَ الْقُرْآنِ',
                'transliteration' => 'Innallaha witrun yuhibbul-witra fa awtiru ya ahlal-qur\'an.',
                'translation' => 'Indeed, Allah is One and He loves the Witr prayer, so perform Witr, O people of the Quran.',
                'source' => 'Sunan Abu Dawud 1416, Jami at-Tirmidhi 453',
                'narrator' => 'Ali ibn Abi Talib',
                'topic' => 'Importance of Witr prayer',
                'verified' => true,
            ],
            [
                'id' => 9,
                'prayer_id' => null, // Special/Tahajjud
                'module' => 'prayer',
                'arabic_text' => 'عَلَيْكُمْ بِقِيَامِ اللَّيْلِ فَإِنَّهُ دَأْبُ الصَّالِحِينَ قَبْلَكُمْ',
                'transliteration' => 'Alaykum bi qiyamil-layli fa innahu da\'bus-salihina qablakum.',
                'translation' => 'Hold fast to night prayer, for indeed it was the practice of the righteous people before you.',
                'source' => 'Jami at-Tirmidhi 3549',
                'narrator' => 'Abu Umamah',
                'topic' => 'Virtue of Tahajjud (Night Prayer)',
                'verified' => true,
            ],
            [
                'id' => 10,
                'prayer_id' => null, // Special/Istikhara
                'module' => 'prayer',
                'arabic_text' => 'إِذَا هَمَّ أَحَدُكُمْ بِالأَمْرِ فَلْيَرْكَعْ رَكْعَتَيْنِ مِنْ غَيْرِ الْفَرِيضَةِ ثُمَّ لْيَقُلْ...',
                'transliteration' => 'Idha hamma ahadukum bil-amri falyarka\' rak\'atayni min ghayril-faridati thumma liyaqul...',
                'translation' => 'If any of you thinks of doing any job, he should pray two rakat other than the compulsory prayers and then say (the dua of Istikhara)...',
                'source' => 'Sahih Bukhari 1162',
                'narrator' => 'Jabir ibn Abdullah',
                'topic' => 'Sunnah of Istikhara prayer',
                'verified' => true,
            ],

            // ================= EATING HADITHS (11-25) =================
            [
                'id' => 11,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'يَا غُلَامُ سَمِّ اللَّهَ وَكُلْ بِيَمِينِكَ وَكُلْ مِمَّا يَلِيكَ',
                'transliteration' => 'Ya ghulamu sammillaha wa kul bi yaminika wa kul mimma yalik.',
                'translation' => 'O young boy, say Bismillah, eat with your right hand, and eat from what is closest to you.',
                'source' => 'Sahih Bukhari 5376, Sahih Muslim 2022',
                'narrator' => 'Umar ibn Abi Salamah',
                'topic' => 'Three golden rules of eating',
                'verified' => true,
            ],
            [
                'id' => 12,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'مَا مَلأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ بِحَسْبِ ابْنِ آدَمَ أُكُلَاتٌ يُقِمْنَ صُلْبَهُ فَإِنْ كَانَ لَا مَحَالَةَ فَثُلُثٌ لِطَعَامِهِ وَثُلُثٌ لِشَرَابِهِ وَثُلُثٌ لِنَفَسِهِ',
                'transliteration' => 'Ma mala\'a adamiyyun wi\'a\'an sharran min batn, bihasbibni adama ukulatin yuqimna sulbah. Fa in kana la mahala fathuluthun lita\'amih, wa thuluthun lisharabih, wa thuluthun linafasih.',
                'translation' => 'A human being fills no vessel worse than his stomach. A few morsels are sufficient for him to keep his spine straight. But if he must, then one third for food, one third for drink, and one third for air.',
                'source' => 'Jami at-Tirmidhi 2380',
                'narrator' => 'Miqdam ibn Ma\'dikarib',
                'topic' => 'Rule of Thirds for Eating',
                'verified' => true,
            ],
            [
                'id' => 13,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'الْبَرَكَةُ تَنْزِلُ وَسَطَ الطَّعَامِ فَكُلُوا مِنْ حَافَتَيْهِ وَلَا تَأْكُلُوا مِنْ وَسَطِهِ',
                'transliteration' => 'Al-barakatu tanzilu wasatat-ta\'am, fakulu min hafatihi wa la ta\'kulu min wasatih.',
                'translation' => 'Blessing descends upon the center of the food, so eat from the sides and do not eat from the center.',
                'source' => 'Jami at-Tirmidhi 1805, Sunan Abu Dawud 3772',
                'narrator' => 'Abdullah ibn Abbas',
                'topic' => 'Eating from the sides of the dish',
                'verified' => true,
            ],
            [
                'id' => 14,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'إِذَا أَكَلَ أَحَدُكُمْ طَعَامًا فَلَا يَمْسَحْ يَدَهُ حَتَّى يَلْعَقَهَا أَوْ يُلْعِقَهَا',
                'transliteration' => 'Idha akala ahadukum ta\'aman fala yamsah yadahu hatta yal\'aqaha aw yul\'iqaha.',
                'translation' => 'When one of you finishes eating, he should not wipe his hand until he has licked his fingers or had them licked.',
                'source' => 'Sahih Bukhari 5409, Sahih Muslim 2031',
                'narrator' => 'Abdullah ibn Abbas',
                'topic' => 'Licking the fingers after eating',
                'verified' => true,
            ],
            [
                'id' => 15,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'مَا عَابَ النَّبِيُّ صلى الله عليه وسلم طَعَامًا قَطُّ إِنِ اشْتَهَاهُ أَكَلَهُ وَإِنْ كَرِهَهُ تَرَكَهُ',
                'transliteration' => 'Ma \'aban-nabiyyu sallallahu alayhi wa sallama ta\'aman qattu, inishtahahu akalahu wa in karihahu tarakah.',
                'translation' => 'The Prophet (ﷺ) never criticized any food; if he liked it, he ate it, and if he disliked it, he left it.',
                'source' => 'Sahih Bukhari 5409, Sahih Muslim 2064',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Never criticizing food',
                'verified' => true,
            ],
            [
                'id' => 16,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'إِذَا وَقَعَتْ لُقْمَةُ أَحَدِكُمْ فَلْيَأْخُذْهَا فَلْيُمِطْ مَا كَانَ بِهَا مِنْ أَذًى وَلْيَأْكُلْهَا وَلَا يَدَعْهَا لِلشَّيْطَانِ',
                'transliteration' => 'Idha waqa\'at luqmatu ahadikum falya\'khudh-ha falyumit ma kana biha min adhan wal-ya\'kulha wa la yada\'ha lish-shaytan.',
                'translation' => 'If a morsel of food falls for one of you, he should pick it up, wipe away any dirt on it, and eat it, and not leave it for Satan.',
                'source' => 'Sahih Muslim 2034',
                'narrator' => 'Jabir ibn Abdullah',
                'topic' => 'Picking up fallen food morsel',
                'verified' => true,
            ],
            [
                'id' => 17,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'تَسَحَّرُوا فَإِنَّ فِي السَّحُورِ بَرَكَةً',
                'transliteration' => 'Tasahharu fa inna fis-sahuri barakah.',
                'translation' => 'Eat Suhoor, for indeed in Suhoor there is blessing.',
                'source' => 'Sahih Bukhari 1923, Sahih Muslim 1095',
                'narrator' => 'Anas ibn Malik',
                'topic' => 'Blessing of Suhoor',
                'verified' => true,
            ],
            [
                'id' => 18,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'لَا تَزَالُ أُمَّتِي بِخَيْرٍ مَا عَجَّلُوا الْفِطْرَ',
                'transliteration' => 'La tazalu ummati bikhayrin ma \'ajjalul-fitr.',
                'translation' => 'My people will continue to be in a good state as long as they hasten to break their fast (Iftar).',
                'source' => 'Sahih Bukhari 1957, Sahih Muslim 1098',
                'narrator' => 'Sahl ibn Sa\'d',
                'topic' => 'Hastening Iftar',
                'verified' => true,
            ],
            [
                'id' => 19,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'إِذَا أَفْطَرَ أَحَدُكُمْ فَلْيُفْطِرْ عَلَى تَمْرٍ فَإِنَّهُ بَرَكَةٌ فَإِنْ لَمْ يَجِدْ فَلْيُفْطِرْ عَلَى مَاءٍ فَإِنَّهُ طَهُورٌ',
                'transliteration' => 'Idha aftara ahadukum falyuftir ala tamrin fa innahu barakah, fa in lam yajid falyuftir ala ma\'in fa innahu tahur.',
                'translation' => 'When one of you breaks his fast, let him do so with dates, for they are a blessing. If he cannot find any, let him break his fast with water, for it is pure.',
                'source' => 'Jami at-Tirmidhi 695',
                'narrator' => 'Salman ibn Amir',
                'topic' => 'Breaking fast with dates or water',
                'verified' => true,
            ],
            [
                'id' => 20,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'إِنَّ اللَّهَ لَيَرْضَى عَنِ الْعَبْدِ أَنْ يَأْكُلَ الأَكْلَةَ فَيَحْمَدَهُ عَلَيْهَا أَوْ يَشْرَبَ الشَّرْبَةَ فَيَحْمَدَهُ عَلَيْهَا',
                'transliteration' => 'Innallaha layarda \'anil-\'abdi an ya\'kulal-aklata fayahmadahu \'alayha aw yashrabash-sharbata fayahmadahu \'alayha.',
                'translation' => 'Indeed, Allah is pleased with a servant when he eats a meal and praises Him for it, or drinks a drink and praises Him for it.',
                'source' => 'Sahih Muslim 2734',
                'narrator' => 'Anas ibn Malik',
                'topic' => 'Praising Allah after eating and drinking',
                'verified' => true,
            ],
            [
                'id' => 21,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'لَا يَشْرَبَنَّ أَحَدٌ مِنْكُمْ قَائِمًا',
                'transliteration' => 'La yashrabanna ahadun minkum qa\'iman.',
                'translation' => 'None of you should drink while standing.',
                'source' => 'Sahih Muslim 2026',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Avoid drinking while standing',
                'verified' => true,
            ],
            [
                'id' => 22,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'نَهَى رَسُولُ اللَّهِ صلى الله عليه وسلم أَنْ يُتَنَفَّسَ فِي الإِنَاءِ أَوْ يُنْفَخَ فِيهِ',
                'transliteration' => 'Naha rasulullahi sallallahu alayhi wa sallama an yutanaffasa fil-ina\'i aw yunfakha fih.',
                'translation' => 'The Messenger of Allah (ﷺ) forbade breathing into the vessel or blowing into it.',
                'source' => 'Jami at-Tirmidhi 1888, Abu Dawud 3728',
                'narrator' => 'Abdullah ibn Abbas',
                'topic' => 'Not breathing or blowing into the cup',
                'verified' => true,
            ],
            [
                'id' => 23,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'الْبَرَكَةُ فِي ثَلَاثَةٍ الْجَمَاعَةِ وَالثَّرِيدِ وَالسُّحُورِ',
                'transliteration' => 'Al-barakatu fi thalathah: al-jama\'ah wat-tharid was-suhur.',
                'translation' => 'Blessing is in three things: congregation, Tharid (a dish of bread and meat broth), and Suhoor.',
                'source' => 'Al-Mu\'jam al-Kabir Al-Tabarani 6127',
                'narrator' => 'Salman Al-Farsi',
                'topic' => 'Eating in group/congregation',
                'verified' => true,
            ],
            [
                'id' => 24,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'مَنْ نَسِيَ وَهُوَ صَائِمٌ فَأَكَلَ أَوْ شَرِبَ فَلْيُتِمَّ صَوْمَهُ فَإِنَّمَا أَطْعَمَهُ اللَّهُ وَسَقَاهُ',
                'transliteration' => 'Man nasiya wa huwa sa\'imun fa akala aw shariba falyutimma sawmahu, fa innama at\'amahullahu wa saqah.',
                'translation' => 'Whoever eats or drinks forgetfully while fasting, let him complete his fast, for it was Allah Who fed him and gave him drink.',
                'source' => 'Sahih Bukhari 1933, Sahih Muslim 1155',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Forgetful eating during fast',
                'verified' => true,
            ],
            [
                'id' => 25,
                'prayer_id' => null,
                'module' => 'eating',
                'arabic_text' => 'عَلَيْكُمْ بِهَذَا الْعُودِ الْهِنْدِيِّ فَإِنَّ فِيهِ سَبْعَةَ أَشْفِيَةٍ',
                'transliteration' => 'Alaykum bi hadhal-\'udil-hindi fa inna fihi sab\'ata ashfiyah.',
                'translation' => 'Use this Indian Oud (Agarwood), for in it is a cure for seven diseases.',
                'source' => 'Sahih Bukhari 5692',
                'narrator' => 'Umm Qays bint Mihsan',
                'topic' => 'Prophetic Medicine and Blessed Herbs',
                'verified' => true,
            ],

            // ================= SUNNAH HADITHS (26-45) =================
            [
                'id' => 26,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'السِّوَاكُ مَطْهَرَةٌ لِلْفَمِ مَرْضَاةٌ لِلرَّبِّ',
                'transliteration' => 'As-siwaku matharatun lil-fami mardatun lir-rabb.',
                'translation' => 'The Siwak (tooth-stick) is a means of purifying the mouth and pleasing the Lord.',
                'source' => 'Sunan an-Nasa\'i 5, Bukhari (mu\'allaq)',
                'narrator' => 'Aisha (ra)',
                'topic' => 'Using Miswak',
                'verified' => true,
            ],
            [
                'id' => 27,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا اسْتَيْقَظَ أَحَدُكُمْ مِنْ نَوْمِهِ فَلَا يَغْمِسْ يَدَهُ فِي الإِنَاءِ حَتَّى يَغْسِلَهَا ثَلَاثًا',
                'transliteration' => 'Idha istayqadha ahadukum min nawmihi fala yaghmis yadahu fil-ina\'i hatta yaghsilaha thalatha.',
                'translation' => 'When one of you wakes up from his sleep, he should not dip his hand in the vessel until he washes it three times.',
                'source' => 'Sahih Muslim 278',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Washing hands upon waking up',
                'verified' => true,
            ],
            [
                'id' => 28,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ',
                'transliteration' => 'Tabassumuka fi wajhi akhika laka sadaqah.',
                'translation' => 'Your smiling in the face of your brother is charity for you.',
                'source' => 'Jami at-Tirmidhi 1956',
                'narrator' => 'Abu Dharr',
                'topic' => 'Smiling in social interaction',
                'verified' => true,
            ],
            [
                'id' => 29,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا دَخَلَ الرَّجُلُ بَيْتَهُ فَذَكَرَ اللَّهَ عِنْدَ دُخُولِهِ وَعِنْدَ طَعَامِهِ قَالَ الشَّيْطَانُ لَا مَبِيتَ لَكُمْ وَلَا عَشَاءَ',
                'transliteration' => 'Idha dakhalar-rajulu baytahu fadhakarallaha inda dukhulihi wa inda ta\'amih, qalash-shaytanu la mabita lakum wa la \'asha\'.',
                'translation' => 'When a man enters his house and mentions Allah upon entering and upon eating, Satan says (to his cohorts): There is no place for you to spend the night and no dinner.',
                'source' => 'Sahih Muslim 2018',
                'narrator' => 'Jabir ibn Abdullah',
                'topic' => 'Remembering Allah when entering home',
                'verified' => true,
            ],
            [
                'id' => 30,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا خَرَجَ الرَّجُلُ مِنْ بَيْتِهِ فَقَالَ بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ يُقَالُ لَهُ هُدِيتَ وَكُفِيتَ وَوُقِيتَ',
                'transliteration' => 'Idha kharajar-rajulu min baytihi faqala: Bismillahi tawakkaltu alallahi la hawla wa la quwwata illa billah. Yuqalu lahu hudita wa kufita wa wuqita.',
                'translation' => 'When a man leaves his house and says: "In the name of Allah, I trust in Allah, there is no power nor strength except in Allah," it is said to him: You are guided, sufficed, and protected.',
                'source' => 'Sunan Abu Dawud 5095, Jami at-Tirmidhi 3426',
                'narrator' => 'Anas ibn Malik',
                'topic' => 'Dua for leaving home',
                'verified' => true,
            ],
            [
                'id' => 31,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'أَفْشُوا السَّلَامَ وَأَطْعِمُوا الطَّعَامَ وَصِلُوا الأَرْحَامَ وَصَلُّوا بِاللَّيْلِ وَالنَّاسُ نِيَامٌ تَدْخُلُوا الْجَنَّةَ بِسَلَامٍ',
                'transliteration' => 'Afshus-salama wa at\'imut-ta\'ama wa silul-arhama wa sallu bil-layli wan-nasu niyamun tadkhulul-jannata bi salam.',
                'translation' => 'Spread peace (Salam), feed people, maintain ties of kinship, and pray at night while others are asleep; you will enter Paradise in peace.',
                'source' => 'Jami at-Tirmidhi 2485, Sunan Ibn Majah 3251',
                'narrator' => 'Abdullah ibn Salam',
                'topic' => 'Spreading Salam and hospitality',
                'verified' => true,
            ],
            [
                'id' => 32,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا أَتَيْتَ مَضْجَعَكَ فَتَوَضَّأْ وُضُوءَكَ لِلصَّلَاةِ ثُمَّ اضْطَجِعْ عَلَى شِقِّكَ الأَيْمَنِ',
                'transliteration' => 'Idha atayta madj\'aka fatawadda\' wudu\'aka lis-salati thumma-dtaji\' ala shiqqikal-ayman.',
                'translation' => 'When you go to bed, perform ablution as you do for prayer, then lie down on your right side.',
                'source' => 'Sahih Bukhari 247, Sahih Muslim 2710',
                'narrator' => 'Al-Bara ibn Azib',
                'topic' => 'Sunnah of sleeping',
                'verified' => true,
            ],
            [
                'id' => 33,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'خَمْسٌ مِنَ الْفِطْرَةِ الْخِتَانُ وَالاِسْتِحْدَادُ وَتَقْلِيمُ الأَظْفَارِ وَنَتْفُ الإِبْطِ وَقَصُّ الشَّارِبِ',
                'transliteration' => 'Khamsun minal-fitrah: al-khitanu wal-istihdadu wa taqlimul-asfari wa natful-ibti wa qassush-sharib.',
                'translation' => 'Five are the acts of Fitrah (natural hygiene): Circumcision, shaving the pubic hair, trimming the fingernails, plucking the armpit hair, and clipping the mustache.',
                'source' => 'Sahih Bukhari 5891, Sahih Muslim 257',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Personal hygiene and Fitrah',
                'verified' => true,
            ],
            [
                'id' => 34,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا تَوَضَّأَ الْعَبْدُ الْمُسْلِمُ أَوْ الْمُؤْمِنُ فَغَسَلَ وَجْهَهُ خَرَجَتْ مِنْ وَجْهِهِ كُلُّ خَطِيئَةٍ نَظَرَ إِلَيْهَا بِعَيْنَيْهِ مَعَ الْمَاءِ',
                'transliteration' => 'Idha tawadda\'al-\'abdul-muslimu awil-mu\'minu faghasala wajhahu kharajat min wajhihi kullu khati\'atin nadhara ilayha bi \'aynayhi ma\'al-ma\'.',
                'translation' => 'When a Muslim or a believer washes his face in course of ablution, every sin he contemplated with his eyes will be washed away from his face with the water.',
                'source' => 'Sahih Muslim 244',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Virtue of Ablution (Wudu)',
                'verified' => true,
            ],
            [
                'id' => 35,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'لَوْلَا أَنْ أَشُقَّ عَلَى أُمَّتِي لأَمَرْتُهُمْ بِالسِّوَاكِ عِنْدَ كُلِّ صَلَاةٍ',
                'transliteration' => 'Lawla an ashuqqa ala ummati la amartuhum bis-siwaki inda kulli salah.',
                'translation' => 'Were it not that I might overgeneralize or burden my nation, I would have ordered them to use the Miswak before every prayer.',
                'source' => 'Sahih Bukhari 887, Sahih Muslim 252',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Siwak before prayer',
                'verified' => true,
            ],
            [
                'id' => 36,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا أُقِيمَتِ الصَّلَاةُ فَلَا تَأْتُوهَا تَسْعَوْنَ وَأْتُوهَا تَمْشُونَ وَعَلَيْكُمُ السَّكِينَةُ',
                'transliteration' => 'Idha uqimatis-salatu fala ta\'tuha tas\'awna wa\'tuha tamshuna wa alaykumus-sakinah.',
                'translation' => 'When the call to prayer is given, do not run to it, but walk with calmness and tranquility.',
                'source' => 'Sahih Bukhari 908, Sahih Muslim 602',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Walking calmly to the masjid',
                'verified' => true,
            ],
            [
                'id' => 37,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا دَخَلَ أَحَدُكُمُ الْمَسْجِدَ فَلْيَرْكَعْ رَكْعَتَيْنِ قَبْلَ أَنْ يَجْلِسَ',
                'transliteration' => 'Idha dakhala ahadukumul-masjida falyarka\' rak\'atayni qabla an yajlis.',
                'translation' => 'When one of you enters the Mosque, he should pray two rakat (Tahiyyat al-Masjid) before sitting down.',
                'source' => 'Sahih Bukhari 444, Sahih Muslim 714',
                'narrator' => 'Abu Qatadah',
                'topic' => 'Tahiyyat al-Masjid',
                'verified' => true,
            ],
            [
                'id' => 38,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'تَعَاوَنُوا عَلَى الْبِرِّ وَالتَّقْوَى',
                'transliteration' => 'Ta\'awanu \'alal-birri wat-taqwa.',
                'translation' => 'Help one another in righteousness and piety.',
                'source' => 'Quran 5:2 (Contextual Hadith support in Bukhari)',
                'narrator' => 'Anas ibn Malik',
                'topic' => 'Helping others and cooperation',
                'verified' => true,
            ],
            [
                'id' => 39,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقًا إِلَى الْجَنَّةِ',
                'transliteration' => 'Man salaka tariqan yaltamisu fihi ilman sahalallahu lahu bihi tariqan ilal-jannah.',
                'translation' => 'Whoever treads a path seeking knowledge, Allah will make easy for him the path to Paradise.',
                'source' => 'Sahih Muslim 2699',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Seeking knowledge',
                'verified' => true,
            ],
            [
                'id' => 40,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ',
                'transliteration' => 'Innallaha rafiqyun yuhibbur-rifqa fil-amri kullih.',
                'translation' => 'Indeed, Allah is Gentle and loves gentleness in all matters.',
                'source' => 'Sahih Bukhari 6927, Sahih Muslim 2593',
                'narrator' => 'Aisha (ra)',
                'topic' => 'Gentleness and kind manners',
                'verified' => true,
            ],
            [
                'id' => 41,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
                'transliteration' => 'La yu\'minu ahadukum hatta yuhibba li akhihi ma yuhibbu li nafsih.',
                'translation' => 'None of you truly believes until he loves for his brother what he loves for himself.',
                'source' => 'Sahih Bukhari 13, Sahih Muslim 45',
                'narrator' => 'Anas ibn Malik',
                'topic' => 'Brotherhood and empathy',
                'verified' => true,
            ],
            [
                'id' => 42,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
                'transliteration' => 'Man kana yu\'minu billahi wal-yawmil-akhiri falyaqul khayran aw liyasmut.',
                'translation' => 'Whoever believes in Allah and the Last Day, let him speak good or remain silent.',
                'source' => 'Sahih Bukhari 6018, Sahih Muslim 47',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Guarding the tongue',
                'verified' => true,
            ],
            [
                'id' => 43,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ',
                'transliteration' => 'Man naffasa an mu\'minin kurbatan min kurabid-dunya naffasallahu anhu kurbatan min kurabi yawmil-qiyamah.',
                'translation' => 'Whoever relieves a believer of some distress in this world, Allah will relieve him of some distress on the Day of Resurrection.',
                'source' => 'Sahih Muslim 2699',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Relieving others distress',
                'verified' => true,
            ],
            [
                'id' => 44,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'إِذَا أَرَادَ أَحَدُكُمْ أَنْ يَنَامَ فَلْيَنْفُضْ فِرَاشَهُ بِدَاخِلَةِ إِزَارِهِ فَإِنَّهُ لَا يَدْرِي مَا خَلَفَهُ عَلَيْهِ',
                'transliteration' => 'Idha arada ahadukum an yanama falyanfud firashahu bi dakhilati izarihi...',
                'translation' => 'When one of you goes to sleep, let him dust his bed with the inner corner of his lower garment, for he does not know what came onto it after him.',
                'source' => 'Sahih Bukhari 6320, Sahih Muslim 2714',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Dusting the bed before sleeping',
                'verified' => true,
            ],
            [
                'id' => 45,
                'prayer_id' => null,
                'module' => 'sunnah',
                'arabic_text' => 'الْكَلِمَةُ الطَّيِّبَةُ صَدَقَةٌ',
                'transliteration' => 'Al-kalimatut-tayyibatu sadaqah.',
                'translation' => 'A good word is a form of charity.',
                'source' => 'Sahih Bukhari 2989, Sahih Muslim 1009',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Speaking good words',
                'verified' => true,
            ],

            // ================= JOB, INCOME, RIZQ, ZAKAT & ETHICS (46-55) =================
            [
                'id' => 46,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'طَلَبُ كَسْبِ الْحَلَالِ فَرِيضَةٌ بَعْدَ الْفَرِيضَةِ',
                'transliteration' => 'Talabu kasbil-halali faridatun ba\'dal-faridah.',
                'translation' => 'Seeking halal livelihood is an obligation after other primary obligations (such as prayers).',
                'source' => 'Shu\'ab al-Iman Al-Bayhaqi 8367',
                'narrator' => 'Abdullah ibn Mas\'ud',
                'topic' => 'Seeking halal income',
                'verified' => true,
            ],
            [
                'id' => 47,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'أَيُّهَا النَّاسُ اتَّقُوا اللَّهَ وَأَجْمِلُوا فِي الطَّلَبِ فَإِنَّ نَفْسًا لَنْ تَمُوتَ حَتَّى تَسْتَوْفِيَ رِزْقَهَا',
                'transliteration' => 'Ayyuhan-nasuttaqullaha wa ajmilu fit-talab, fa inna nafsan lan tamuta hatta tastawfiya rizqaha.',
                'translation' => 'O people, fear Allah and be moderate in seeking a living, for indeed no soul will die until it has received its provision in full.',
                'source' => 'Sunan Ibn Majah 2235',
                'narrator' => 'Jabir ibn Abdullah',
                'topic' => 'Trust in Allah for Rizq (Sustenance)',
                'verified' => true,
            ],
            [
                'id' => 48,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'مَا أَكَلَ أَحَدٌ طَعَامًا قَطُّ خَيْرًا مِنْ أَنْ يَأْكُلَ مِنْ عَمَلِ يَدِهِ وَإِنَّ نَبِيَّ اللَّهِ دَاوُدَ كَانَ يَأْكُلُ مِنْ عَمَلِ يَدِهِ',
                'transliteration' => 'Ma akala ahadun ta\'aman qattu khayran min an ya\'kula min amali yadih, wa inna nabiyyallahi Dawuda kana ya\'kulu min amali yadih.',
                'translation' => 'No one has ever eaten any food better than that which he earned with the work of his own hands. Indeed, the Prophet of Allah, David (peace be upon him), used to eat from the work of his own hands.',
                'source' => 'Sahih Bukhari 2072',
                'narrator' => 'Miqdam ibn Ma\'dikarib',
                'topic' => 'Manual labor and earning with hands',
                'verified' => true,
            ],
            [
                'id' => 49,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'لَعَنَ رَسُولُ اللَّهِ صلى الله عليه وسلم آكِلَ الرِّبَا وَمُوكِلَهُ وَكَاتِبَهُ وَشَاهِدَيْهِ وَقَالَ هُمْ سَوَاءٌ',
                'transliteration' => 'La\'ana rasulullahi sallallahu alayhi wa sallama akilar-riba wa mukilahu wa katibahu wa shahidayhi, wa qala hum sawa\'.',
                'translation' => 'The Messenger of Allah (ﷺ) cursed the one who consumes ribā (usury/interest), the one who pays it, the one who writes it down, and the two who witness it, and he said: "They are all equal (in sin)."',
                'source' => 'Sahih Muslim 1598',
                'narrator' => 'Jabir ibn Abdullah',
                'topic' => 'Prohibition of Riba (Interest)',
                'verified' => true,
            ],
            [
                'id' => 50,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'الْبَيِّعَانِ بِالْخِيَارِ مَا لَمْ يَتَفَرَّقَا فَإِنْ صَدَقَا وَبَيَّنَا بُورِكَ لَهُمَا فِي بَيْعِهِمَا وَإِنْ كَتَمَا وَكَذَبَا مُحِقَتْ بَرَكَةُ بَيْعِهِمَا',
                'transliteration' => 'Al-bayyi\'ani bil-khiyari ma lam yatafarraqa, fa in sadaqa wa bayyana burika lahuma fi bay\'ihima, wa in katama wa kadhaba muhiqat barakatu bay\'ihima.',
                'translation' => 'The buyer and the seller have the option to cancel the transaction as long as they have not parted. If they are truthful and clarify defects, their transaction will be blessed. But if they lie and hide defects, the blessing of their transaction will be wiped out.',
                'source' => 'Sahih Bukhari 2079, Sahih Muslim 1532',
                'narrator' => 'Hakim ibn Hizam',
                'topic' => 'Honesty and transparency in business',
                'verified' => true,
            ],
            [
                'id' => 51,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'رَحِمَ اللَّهُ رَجُلاً سَمْحًا إِذَا بَاعَ وَإِذَا اشْتَرَى وَإِذَا اقْتَضَى',
                'transliteration' => 'Rahimallahu rajulan samhan idha ba\'a wa idhashtara wa idhaqtada.',
                'translation' => 'May Allah show mercy to a man who is kind and easygoing when he sells, when he buys, and when he demands his debts.',
                'source' => 'Sahih Bukhari 2076',
                'narrator' => 'Jabir ibn Abdullah',
                'topic' => 'Kindness in buying and selling',
                'verified' => true,
            ],
            [
                'id' => 52,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'مَنْ غَشَّنَا فَلَيْسَ مِنَّا',
                'transliteration' => 'Man ghashana falaysa minna.',
                'translation' => 'Whoever cheats us is not one of us.',
                'source' => 'Sahih Muslim 102',
                'narrator' => 'Abu Hurayrah',
                'topic' => 'Prohibition of cheating and fraud',
                'verified' => true,
            ],
            [
                'id' => 53,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'أَعْطُوا الأَجِيرَ أَجْرَهُ قَبْلَ أَنْ يَجِفَّ عَرَقُهُ',
                'transliteration' => 'A\'tul-ajira ajrahu qabla an yajiffa araquh.',
                'translation' => 'Give the worker his wages before his sweat dries.',
                'source' => 'Sunan Ibn Majah 2443',
                'narrator' => 'Abdullah ibn Umar',
                'topic' => 'Prompt payment of worker wages',
                'verified' => true,
            ],
            [
                'id' => 54,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'إِنَّ اللَّهَ فَرَضَ عَلَيْهِمْ صَدَقَةً فِي أَمْوَالِهِمْ تُؤْخَذُ مِنْ أَغْنِيَائِهِمْ وَتُرَدُّ عَلَى فُقَرَائِهِمْ',
                'transliteration' => 'Innallaha farada alayhim sadaqatan fi amwalihim tu\'khadhu min aghniya\'ihim wa turaddu ala fuqara\'ihim.',
                'translation' => 'Indeed, Allah has obligated upon them charity (Zakat) from their wealth, to be taken from their rich and given to their poor.',
                'source' => 'Sahih Bukhari 1395, Sahih Muslim 19',
                'narrator' => 'Abdullah ibn Abbas',
                'topic' => 'Obligation of Zakat',
                'verified' => true,
            ],
            [
                'id' => 55,
                'prayer_id' => null,
                'module' => 'income',
                'arabic_text' => 'مَنْ لَا يَشْكُرِ النَّاسَ لَا يَشْكُرِ اللَّهَ',
                'transliteration' => 'Man la yashkurin-nasa la yashkurillah.',
                'translation' => 'Whoever does not thank people does not thank Allah.',
                'source' => 'Jami at-Tirmidhi 1954',
                'narrator' => 'Abu Sa\'id Al-Khudri',
                'topic' => 'Gratitude and ethical business ties',
                'verified' => true,
            ],
        ];

        foreach ($hadiths as $hadith) {
            Hadith::updateOrCreate(['id' => $hadith['id']], $hadith);
        }
    }
}
