<?php

namespace Database\Seeders;

use App\Models\IslamicFinanceConcept;
use Illuminate\Database\Seeder;

class IslamicFinanceConceptSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $concepts = [
            [
                'name' => 'Mudarabah',
                'arabic_name' => 'المضاربة',
                'description' => 'A partnership contract where one party provides the entire capital (Rab-ul-Mal) and the other party provides the expertise and labor (Mudarib). Profits are shared according to a pre-agreed ratio, whereas financial losses are borne solely by the capital provider, unless there is proven negligence by the manager.',
                'example' => 'An Islamic bank provides $100,000 to an entrepreneur to launch a retail store. The agreed profit split is 60% for the entrepreneur and 40% for the bank. If the business makes profit, they share it 60/40. If it suffers a loss without manager fault, the bank loses its capital and the entrepreneur loses their effort.',
                'hadith_id' => 50,
            ],
            [
                'name' => 'Musharakah',
                'arabic_name' => 'المشاركة',
                'description' => 'A joint-venture partnership where all partners contribute both capital and labor/expertise. Profits are distributed according to a mutual agreement, while losses must be shared strictly in proportion to each partner\'s capital contribution.',
                'example' => 'Two partners buy a delivery truck for $30,000. Partner A contributes $20,000 (2/3) and Partner B contributes $10,000 (1/3). They agree to split profits 50/50 for their active labor. However, if the truck is damaged or lost, the loss must be shared strictly in accordance with their capital shares: A bears 66.6% and B bears 33.3% of the loss.',
                'hadith_id' => 50,
            ],
            [
                'name' => 'Murabaha',
                'arabic_name' => 'المرابحة',
                'description' => 'A cost-plus sale contract where the seller purchases an asset requested by the client, and then sells it to the client at a marked-up price (cost + profit). The client pays in installments over a specified period. This is an alternative to standard interest-bearing loans.',
                'example' => 'A customer wants to buy a car costing $20,000 but doesn\'t have cash. The Islamic bank buys the car from the dealer for $20,000, takes ownership of it, and sells it to the customer for $24,000, to be paid in monthly installments of $400 over 5 years. This is a trading transaction with a fixed mark-up, not a money-lending interest loan.',
                'hadith_id' => 51,
            ],
            [
                'name' => 'Ijara',
                'arabic_name' => 'الإجارة',
                'description' => 'A leasing contract where the owner of an asset (lessor) transfers the right of use (usufruct) of the asset to another party (lessee) for an agreed period in exchange for rent payments. The ownership and ultimate risk of the asset remain with the lessor.',
                'example' => 'An Islamic bank buys a printing press and leases it to a publishing house for 3 years at a rent of $1,000 per month. The bank remains the owner and maintains insurance/major repair duties, while the publisher uses it and pays monthly rent.',
                'hadith_id' => 53,
            ],
            [
                'name' => 'Sukuk',
                'arabic_name' => 'الصكوك',
                'description' => 'Shariah-compliant investment certificates (often called "Islamic bonds") that represent an undivided fractional ownership share in tangible assets, services, or project operations, rather than a debt claim. Sukuk holders receive a share of profits generated by the underlying assets.',
                'example' => 'A government wants to build a new airport. Instead of issuing interest-bearing treasury bonds, it issues Sukuk. Investors buy the Sukuk, making them co-owners of the airport terminal. They receive a share of the actual rental income or service fees generated by the airport.',
                'hadith_id' => 50,
            ],
            [
                'name' => 'Takaful',
                'arabic_name' => 'التكافل',
                'description' => 'Shariah-compliant mutual insurance based on the principles of cooperation, shared responsibility, and donation (Tabarru). Participants contribute money to a common pool to assist any member who suffers a defined loss, avoiding the interest (Riba) and uncertainty (Gharar) of conventional insurance.',
                'example' => 'A group of 1,000 car owners establish a Takaful fund. Each contributes $500 annually as a donation (Tabarru). When a participant meets with an accident, their car repair cost is paid out from this collective pool. Any surplus remaining in the pool at the end of the year is returned to the participants.',
                'hadith_id' => 43,
            ],
            [
                'name' => 'Qard Hasan',
                'arabic_name' => 'القرض الحسن',
                'description' => 'An interest-free loan (literally "beautiful loan") extended out of goodwill and charity. The borrower is only obligated to repay the principal amount borrowed, without any extra charges. The lender expects reward only from Allah.',
                'example' => 'A friend needs $2,000 to pay medical bills. You lend them $2,000 with an agreement that they will repay it in 10 months ($200/month). Charging any extra fee or interest would be Riba, but lending it free of charge is a highly rewarded Qard Hasan.',
                'hadith_id' => 51,
            ],
        ];

        foreach ($concepts as $concept) {
            IslamicFinanceConcept::create($concept);
        }
    }
}
