<?php

namespace Database\Seeders;

use App\Models\Sunnah;
use Illuminate\Database\Seeder;

class SunnahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sunnahs = [
            // Sleep Sunnahs
            [
                'title' => 'Sleeping in a State of Ablution (Wudu)',
                'arabic_title' => 'النوم على وضوء',
                'description' => 'Performing a complete wudu (ablution) just like the one for prayer before going to bed.',
                'category' => 'sleep',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'night',
                'hadith_id' => 32,
                'order_number' => 1,
            ],
            [
                'title' => 'Dusting the Bed Three Times',
                'arabic_title' => 'نفض الفراش',
                'description' => 'Dusting the bed sheets or surface three times with the corner of a garment before lying down.',
                'category' => 'sleep',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'night',
                'hadith_id' => 44,
                'order_number' => 2,
            ],
            [
                'title' => 'Sleeping on the Right Side',
                'arabic_title' => 'النوم على الجانب الأيمن',
                'description' => 'Lying down on your right side with the right hand placed under the right cheek upon going to sleep.',
                'category' => 'sleep',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'night',
                'hadith_id' => 32,
                'order_number' => 3,
            ],

            // Hygiene Sunnahs
            [
                'title' => 'Using the Tooth-stick (Miswak)',
                'arabic_title' => 'السواك',
                'description' => 'Using the Miswak or brush to clean teeth, especially when waking up, before wudu, and before entering the home.',
                'category' => 'hygiene',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 26,
                'order_number' => 4,
            ],
            [
                'title' => 'Washing Hands Upon Waking Up',
                'arabic_title' => 'غسل اليدين عند الاستيقاظ',
                'description' => 'Washing both hands three times before dipping them into any water vessel or starting other activities after waking up.',
                'category' => 'hygiene',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'morning',
                'hadith_id' => 27,
                'order_number' => 5,
            ],
            [
                'title' => 'Trimming Nails Regularly',
                'arabic_title' => 'تقليم الأظفار',
                'description' => 'Trimming fingernails and toenails on a weekly basis, preferably on Fridays, as part of natural fitrah.',
                'category' => 'hygiene',
                'difficulty' => 'easy',
                'is_daily' => false,
                'time_of_day' => 'general',
                'hadith_id' => 33,
                'order_number' => 6,
            ],

            // Eating Sunnahs
            [
                'title' => 'Saying Bismillah before Eating',
                'arabic_title' => 'التسمية عند الأكل',
                'description' => 'Saying "Bismillah" (In the name of Allah) before taking the first bite of food.',
                'category' => 'eating',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 11,
                'order_number' => 7,
            ],
            [
                'title' => 'Eating with the Right Hand',
                'arabic_title' => 'الأكل باليمين',
                'description' => 'Using only the right hand to eat and drink, as the left hand is used for cleaning and is associated with satanic habits.',
                'category' => 'eating',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 11,
                'order_number' => 8,
            ],
            [
                'title' => 'Eating what is Nearest',
                'arabic_title' => 'الأكل مما يليك',
                'description' => 'Eating from the side of the platter closest to you rather than reaching into the center or to others\' sides.',
                'category' => 'eating',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 11,
                'order_number' => 9,
            ],
            [
                'title' => 'Licking the Fingers after Eating',
                'arabic_title' => 'لعق الأصابع بعد الأكل',
                'description' => 'Licking the thumb, index, and middle fingers after finishing the meal before washing hands.',
                'category' => 'eating',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 14,
                'order_number' => 10,
            ],
            [
                'title' => 'Not Criticizing Food',
                'arabic_title' => 'عدم عيب الطعام',
                'description' => 'Refraining from making negative remarks about food. If you like it, eat it; if you do not, leave it silently.',
                'category' => 'eating',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 15,
                'order_number' => 11,
            ],
            [
                'title' => 'Picking up Fallen Food',
                'arabic_title' => 'أكل اللقمة الساقطة',
                'description' => 'If a morsel falls down, clean off any dirt and eat it instead of leaving it for Satan.',
                'category' => 'eating',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 16,
                'order_number' => 12,
            ],
            [
                'title' => 'Eating Together in Groups',
                'arabic_title' => 'الأكل جماعة',
                'description' => 'Eating with family members, guests, or in groups, as blessings descend upon collective meals.',
                'category' => 'eating',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 23,
                'order_number' => 13,
            ],
            [
                'title' => 'Drinking Water while Sitting',
                'arabic_title' => 'الشرب جالسا',
                'description' => 'Sitting down before drinking water or other beverages instead of drinking standing up.',
                'category' => 'eating',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 21,
                'order_number' => 14,
            ],
            [
                'title' => 'Avoiding Blowing in Hot Drinks',
                'arabic_title' => 'عدم النفخ في الشراب',
                'description' => 'Letting hot food or drinks cool down naturally instead of blowing into them.',
                'category' => 'eating',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 22,
                'order_number' => 15,
            ],

            // Social Sunnahs
            [
                'title' => 'Spreading Salam (Greetings)',
                'arabic_title' => 'إفشاء السلام',
                'description' => 'Greeting others with "Assalamu Alaikum" (Peace be upon you) when meeting, whether you know them or not.',
                'category' => 'social',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 31,
                'order_number' => 16,
            ],
            [
                'title' => 'Smiling in the Face of Others',
                'arabic_title' => 'التبسم',
                'description' => 'Maintaining a friendly face and smiling when interacting with family, friends, or strangers.',
                'category' => 'social',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 28,
                'order_number' => 17,
            ],
            [
                'title' => 'Speaking Good Words or Keeping Silent',
                'arabic_title' => 'قول الخير أو الصمت',
                'description' => 'Consciously guarding your tongue, choosing to say only beneficial, kind words or remaining silent.',
                'category' => 'social',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 42,
                'order_number' => 18,
            ],
            [
                'title' => 'Gentleness and Kindness in Speech',
                'arabic_title' => 'الرفق في الكلام',
                'description' => 'Being soft-spoken and gentle in all dealings, avoiding harshness and rude expressions.',
                'category' => 'social',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 40,
                'order_number' => 19,
            ],

            // Worship / Prayer Sunnahs
            [
                'title' => 'Two Rakat Sunnah Before Fajr',
                'arabic_title' => 'سنة الفجر',
                'description' => 'Praying two rakat of highly emphasized Sunnah prayer before the Fard of Fajr.',
                'category' => 'worship',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'morning',
                'hadith_id' => 2,
                'order_number' => 20,
            ],
            [
                'title' => 'Four Rakat Sunnah Before Dhuhr',
                'arabic_title' => 'أربع ركعات قبل الظهر',
                'description' => 'Consistently observing four rakat of voluntary/sunnah prayer before Dhuhr Fard.',
                'category' => 'worship',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'afternoon',
                'hadith_id' => 3,
                'order_number' => 21,
            ],
            [
                'title' => 'Walking Calmly to the Mosque',
                'arabic_title' => 'المشي إلى المسجد بسكينة',
                'description' => 'Walking to the mosque with calmness, composure, and dignity rather than rushing or running.',
                'category' => 'worship',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 36,
                'order_number' => 22,
            ],
            [
                'title' => 'Tahiyyat al-Masjid (Mosque Greeting Prayer)',
                'arabic_title' => 'تحية المسجد',
                'description' => 'Praying two voluntary rakat immediately upon entering the mosque before sitting down.',
                'category' => 'worship',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 37,
                'order_number' => 23,
            ],
            [
                'title' => 'Performing the Witr Prayer',
                'arabic_title' => 'صلاة الوتر',
                'description' => 'Praying the Witr prayer (odd number of rakat) as the final prayer of the night, either before sleeping or at Tahajjud.',
                'category' => 'worship',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'night',
                'hadith_id' => 8,
                'order_number' => 24,
            ],
            [
                'title' => 'Praying the Voluntary Night Prayer (Tahajjud)',
                'arabic_title' => 'قيام الليل',
                'description' => 'Waking up in the final third of the night to pray voluntary prayers (Qiyam-ul-Layl).',
                'category' => 'worship',
                'difficulty' => 'advanced',
                'is_daily' => true,
                'time_of_day' => 'night',
                'hadith_id' => 9,
                'order_number' => 25,
            ],

            // Travel & General Sunnahs
            [
                'title' => 'Dua when Leaving the House',
                'arabic_title' => 'دعاء الخروج من المنزل',
                'description' => 'Reciting "Bismillahi tawakkaltu alallahi..." when stepping out of the house for protection and guidance.',
                'category' => 'travel',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 30,
                'order_number' => 26,
            ],
            [
                'title' => 'Mentioning Allah when Entering the House',
                'arabic_title' => 'ذكر الله عند دخول المنزل',
                'description' => 'Saying "Bismillah" and greeting the family with Salam when stepping inside the home to expel Satan.',
                'category' => 'general',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 29,
                'order_number' => 27,
            ],
            [
                'title' => 'Seeking Beneficial Knowledge',
                'arabic_title' => 'طلب العلم',
                'description' => 'Dedicating time daily to read, learn, and understand Islamic rules, Quran, and Hadiths.',
                'category' => 'general',
                'difficulty' => 'medium',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 39,
                'order_number' => 28,
            ],
            [
                'title' => 'Relieving Another\'s Distress',
                'arabic_title' => 'تفريج الكرب',
                'description' => 'Actively assisting someone in financial, emotional, or practical hardship to ease their life.',
                'category' => 'social',
                'difficulty' => 'advanced',
                'is_daily' => false,
                'time_of_day' => 'general',
                'hadith_id' => 43,
                'order_number' => 29,
            ],
            [
                'title' => 'Speaking Kind Words to Others',
                'arabic_title' => 'الكلمة الطيبة',
                'description' => 'Using pleasant and encouraging words when talking to coworkers, neighbors, family, and strangers.',
                'category' => 'social',
                'difficulty' => 'easy',
                'is_daily' => true,
                'time_of_day' => 'general',
                'hadith_id' => 45,
                'order_number' => 30,
            ],
        ];

        foreach ($sunnahs as $sunnah) {
            Sunnah::create($sunnah);
        }
    }
}
